[tox]
envlist = py38,py39,py310,py311,py312,lint,type

[testenv]
deps = -r{toxinidir}/requirements-dev.txt
commands = pytest tests/ -v

[testenv:lint]
commands = ruff check passive_aggressive_reminder_bot tests

[testenv:type]
commands = mypy passive_aggressive_reminder_bot

[testenv:format]
commands = black passive_aggressive_reminder_bot tests
